---
# _service_state: stopped | started
- name: Manage EDA services
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.operations
    tasks_from: manage_service.yml
  vars:
    component_name: "{{ automationeda_component_name }}"
