---
# _service_state: stopped | started
- name: Manage monitoring service
  ansible.builtin.systemd:
    name: pcp
    state: "{{ _service_state }}"
    scope: user
  when: aap_platform == 'containerized'
