---
galaxy_info:
  role_name: import_ocp
  author: Red Hat
  description: Import an AAP artifact into an OCP operator-based deployment
  license: GPL-3.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
dependencies: []
