---
# Parametrized service management for all AAP components.
# _service_state: stopped | started
- name: Monitoring (pre)
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.pcp
    tasks_from: manage_service.yml
  when: _service_state == 'stopped'

- name: EDA services
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.automationeda
    tasks_from: manage_service.yml
  when: inventory_hostname in groups.get('eda_groups', [])

- name: Hub services
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.automationhub
    tasks_from: manage_service.yml
  when: inventory_hostname in groups.get('hub_groups', [])

- name: Controller services
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.automationcontroller
    tasks_from: manage_service.yml
  when: inventory_hostname in groups.get('controller_groups', [])

- name: Gateway services
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.automationgateway
    tasks_from: manage_service.yml
  when: inventory_hostname in groups.get('gateway_groups', [])

- name: Monitoring (post)
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.pcp
    tasks_from: manage_service.yml
  when: _service_state == 'started'
