---
- name: Set component config
  ansible.builtin.set_fact:
    _operations_current_component: "{{ _operations_component_config[component_name] }}"

- name: "Restore database"
  ansible.builtin.include_role:
    name: ansible.aap_snapshot.postgresql
    tasks_from: db_import.yml
  vars:
    postgresql_component_name: "{{ component_name }}"
    postgresql_restore_source: "{{ __operations_artifact_extract_dir }}/{{ component_name }}/{{ component_name }}.pgc"
...
