---
name: Collection Certification

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  certification:
    uses: ansible-collections/partner-certification-checker/.github/workflows/certification-reusable.yml@f4bf7ba4d3f008b2db8fc6a812fa3f89fdf42c2e # v4.1.0
