---
name: Collection Certification

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  certification:
    uses: ansible-collections/partner-certification-checker/.github/workflows/certification-reusable.yml@f182febf0568baf1151f66549401167fd10b25d2 # v4.0.0
