---
name: Collection Certification

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  certification:
    uses: ansible-collections/partner-certification-checker/.github/workflows/certification-reusable.yml@31ef407dd12d185388fe0c278eba9fc8bbec2e15 # v3.0.1
